FROM  python:3.9

WORKDIR /code

COPY requirements.txt /code/requirements.txt
COPY hello.py /code/hello.py

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

CMD ["python","hello.py"]